import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navbar/Navbar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import MainLayout from "@/Component/MainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Junayet | WEB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Junayet | WEB</title>
      <body className={inter.className}>
      <MainLayout>{children}</MainLayout>
        </body>
    </html>
  );
}
