"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navbar/Navbar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "@/Component/Footer/Footer";
import ContextProvider, { ThemContext } from "@/Component/Context/ThemContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Junayet | WEB",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Junayet | WEB</title>
      <body className={inter.className}>
        <>
        <ContextProvider>
        <ThemContext.Consumer>
            {(value) => (
              <div className={value.Light === "light" ? "light-mode" : "dark-mode"}>
                <Navbar />
                {children}
                <Footer />
              </div>
            )}
          </ThemContext.Consumer>
        </ContextProvider>
        </>
        </body>
    </html>
  );
}
